---
# tasks file for mariadb

- name: Ajout du repot epel release
  become: yes
  remote_user: jpereira
  yum:
   name: epel-release
   state: present

- name: Install mariadb
  become: yes
  remote_user: jpereira
  yum: 
   name: "{{ item }}"
   state: present
  loop: "{{ install }}"

- name: Création fichier client mariadb
  copy:
    dest: /home/jpereira/my.cnf
    content: |
      [client]
      user=root
      password=""

- name: Mysql droits
  become: yes
  mysql_user:
    state: present
    name: jpereira
    password: jpereira
    priv:
      '*.*:ALL,GRANT'
    host: 192.168.1.27


- name: Rédemarrage mariadb
  become: yes
  systemd:
    name: mariadb
    state: restarted
