---
# tasks file for httpd-php
  
- name: Création d'un utilisateur
  user:
    name: jpereira
    comment: "Utilisateur pour ansible"
    shell: /bin/bash
- name: Ajout de la clé SSH
  authorized_key:
     user: jpereira
     state: present
     key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  
- name: Ajout de jpereira dans sudo
  template:
    src: sudoers.j2
    dest: /etc/sudoers.d/jpereira

- name: Installation httpd et php
  become_user: yes
  remote_user: jpereira
  yum:
    name: "{{ item }}"
    state: present
  loop:
    "{{ install }}"

- name: Copie des fichiers php
  become: yes
  copy:
    src: db-data
    dest: /var/www/html

- name: Changer le document root
  become: yes
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DocumentRoot '
    insertafter: '^#DocumentRoot '
    line: 'DocumentRoot "/var/www/html/db-data"'

- name: Ajout fichier db.conf
  become: yes
  template:
    src: "templates/db-config.php.j2"
    dest: /var/www/html/db-data/db-config.php


- name: Suppresion welcome.conf
  become: yes
  file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Restart httpd
  become: yes
  systemd:
    name: httpd
    state: restarted


